# scripts/feeds.py

FEEDS = [
    {"id": "morikinoko_com", "name": "SS 森きのこ！", "url": "http://morikinoko.com/index.rdf"},
    {"id": "blog_livedoor_jp_nwknews", "name": "哲学ニュースnwk", "url": "http://blog.livedoor.jp/nwknews/index.rdf"},
    {"id": "news4vip_livedoor_biz", "name": "【2ch】ニュー速クオリティ", "url": "http://news4vip.livedoor.biz/index.rdf"},
    {"id": "matometanews_com", "name": "まとめたニュース", "url": "http://matometanews.com/index.rdf"},
    {"id": "blog_livedoor_jp_jyoushiki43", "name": "常識的に考えた", "url": "http://blog.livedoor.jp/jyoushiki43/index.rdf"},
    {"id": "blog_livedoor_jp_dqnplus", "name": "痛いニュース(ﾉ∀`)", "url": "http://blog.livedoor.jp/dqnplus/index.rdf"},
    {"id": "blog_livedoor_jp_yu_ps13", "name": "ゆめ痛 -NEWS ALERT-", "url": "http://blog.livedoor.jp/yu_ps13/index.rdf"},
    {"id": "blog_livedoor_jp_misopan_news", "name": "みそパンNEWS", "url": "http://blog.livedoor.jp/misopan_news/index.rdf"},
    {"id": "blog_livedoor_jp_gotagotashita", "name": "ゴタゴタシタニュース", "url": "http://blog.livedoor.jp/gotagotashita/index.rdf"},
    {"id": "www_news30over_com", "name": "ニュース30over", "url": "http://www.news30over.com/index.rdf"},
    {"id": "blog_livedoor_jp_funs", "name": "ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ", "url": "http://blog.livedoor.jp/funs/index.rdf"},
    {"id": "ryusoku_com", "name": "流速VIP", "url": "http://ryusoku.com/index.rdf"},
    {"id": "kuromacyo_livedoor_biz", "name": "黒マッチョニュース", "url": "http://kuromacyo.livedoor.biz/index.rdf"},
    {"id": "www_scienceplus2ch_com", "name": "(*ﾟ∀ﾟ)ゞカガクニュース隊", "url": "http://www.scienceplus2ch.com/index.rdf"},
    {"id": "blog_livedoor_jp_news23vip", "name": "VIPPERな俺", "url": "http://blog.livedoor.jp/news23vip/index.rdf"},
    {"id": "burusoku_vip_com", "name": "ぶる速-VIP", "url": "http://burusoku-vip.com/index.rdf"},
    {"id": "hamusoku_com", "name": "ハムスター速報", "url": "http://hamusoku.com/index.rdf"},
    {"id": "kanasoku_info", "name": "カナ速", "url": "http://kanasoku.info/index.rdf"},
    {"id": "blog_livedoor_jp_goldennews", "name": "ゴールデンタイムズ", "url": "http://blog.livedoor.jp/goldennews/index.rdf"},
    {"id": "workingnews_blog117_fc2_com", "name": "働くモノニュース : 人生VIP職人ブログwww", "url": "http://workingnews.blog117.fc2.com/?xml"},
    {"id": "digital_thread_com", "name": "デジタルニューススレッド", "url": "http://digital-thread.com/index.rdf"},
    {"id": "chaos2ch_com", "name": "カオスちゃんねる", "url": "http://chaos2ch.com/index.rdf"},
    {"id": "blog_livedoor_jp_kinisoku", "name": "キニ速", "url": "http://blog.livedoor.jp/kinisoku/index.rdf"},
    {"id": "michaelsan_livedoor_biz", "name": "もみあげチャ～シュ～", "url": "http://michaelsan.livedoor.biz/index.rdf"},
    {"id": "alfalfalfa_com", "name": "アルファルファモザイク", "url": "http://alfalfalfa.com/index.rdf"},
    {"id": "lifehack2ch_livedoor_biz", "name": "ライフハックちゃんねる弐式", "url": "http://lifehack2ch.livedoor.biz/index.rdf"},
    {"id": "blog_livedoor_jp_kekkongo", "name": "結婚・恋愛ニュースぷらす", "url": "http://blog.livedoor.jp/kekkongo/index.rdf"},
    {"id": "onecall2ch_com", "name": "わんこーる速報！", "url": "http://onecall2ch.com/index.rdf"},
    {"id": "blog_livedoor_jp_robosoku", "name": "ろぼ速VIP", "url": "http://blog.livedoor.jp/robosoku/index.rdf"},
    {"id": "blog_esuteru_com", "name": "はちま起稿", "url": "http://blog.esuteru.com/index.rdf"},
    {"id": "jin115_com", "name": "オレ的ゲーム速報＠刃", "url": "http://jin115.com/index.rdf"},
    {"id": "2chcopipe_com", "name": "2chコピペ保存道場", "url": "http://2chcopipe.com/index.rdf"},
    {"id": "otakomu_jp", "name": "オタク.com", "url": "http://otakomu.jp/index.rdf"},
    {"id": "cherio199_blog120_fc2_com", "name": "ヒロイモノ中毒", "url": "http://cherio199.blog120.fc2.com/?xml"},
    {"id": "honwaka2ch_livedoor_biz", "name": "ほんわかMkⅡ", "url": "http://honwaka2ch.livedoor.biz/index.rdf"},
    {"id": "blog_livedoor_jp_nanjstu", "name": "なんじぇいスタジアム＠なんJまとめ", "url": "http://blog.livedoor.jp/nanjstu/index.rdf"},
    {"id": "military38_com", "name": "大艦巨砲主義！", "url": "http://military38.com/index.rdf"},
    {"id": "hosyusokuhou_jp", "name": "保守速報", "url": "http://hosyusokuhou.jp/index.rdf"},
    {"id": "www_akb48matomemory_com", "name": "NEWSまとめもりー｜2chまとめブログ", "url": "http://www.akb48matomemory.com/index.rdf"},
    {"id": "usi32_com", "name": "うしみつ-2ch怖い話まとめ-", "url": "http://usi32.com/index.rdf"},
    {"id": "gundamlog_com", "name": "GUNDAM.LOG｜ガンダムまとめブログ", "url": "http://gundamlog.com/index.rdf"},
    {"id": "blog_livedoor_jp_diet2channel", "name": "ダイエット速報＠2ちゃんねる", "url": "http://blog.livedoor.jp/diet2channel/index.rdf"},
    {"id": "world_fusigi_net", "name": "不思議.net", "url": "http://world-fusigi.net/index.rdf"},
    {"id": "vippers_jp", "name": "VIPPER速報", "url": "http://vippers.jp/index.rdf"},
    {"id": "blog_livedoor_jp_yakiusoku", "name": "日刊やきう速報＠野球まとめ", "url": "http://blog.livedoor.jp/yakiusoku/index.rdf"},
    {"id": "rabitsokuhou_2chblog_jp", "name": "ラビット速報", "url": "http://rabitsokuhou.2chblog.jp/index.rdf"},
    {"id": "f1jouhou2_blog_fc2_com", "name": "F1情報通", "url": "http://f1jouhou2.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_kaikaihanno", "name": "カイカイ反応通信", "url": "http://blog.livedoor.jp/kaikaihanno/index.rdf"},
    {"id": "www_honmotakeshi_com", "name": "正義の見方", "url": "https://www.honmotakeshi.com/feed"},
    {"id": "www_saikyo_jump_com", "name": "最強ジャンプ放送局", "url": "http://www.saikyo-jump.com/index.rdf"},
    {"id": "blog_livedoor_jp_bbyakyu", "name": "竜速（りゅうそく）", "url": "http://blog.livedoor.jp/bbyakyu/index.rdf"},
    {"id": "aramame_net", "name": "あらまめ2ch", "url": "http://aramame.net/feed"},
    {"id": "blog_livedoor_jp_livejupiter2", "name": "なんJ（まとめては）いかんのか？", "url": "http://blog.livedoor.jp/livejupiter2/index.rdf"},
    {"id": "blog_livedoor_jp_fightersmatome", "name": "ポリー速報", "url": "http://blog.livedoor.jp/fightersmatome/index.rdf"},
    {"id": "geinoukame_blog_fc2_com", "name": "芸能かめはめ波", "url": "http://geinoukame.blog.fc2.com/?xml"},
    {"id": "jumpsokuhou_com", "name": "ジャンプ速報", "url": "http://jumpsokuhou.com/index.rdf"},
    {"id": "matomelotte_com", "name": "まとめロッテ！", "url": "http://matomelotte.com/index.rdf"},
    {"id": "gossip1_net", "name": "GOSSIP速報", "url": "http://gossip1.net/index.rdf"},
    {"id": "sakarabo_blog_jp", "name": "サカラボ | サッカーまとめ速報", "url": "http://sakarabo.blog.jp/index.rdf"},
    {"id": "www_calciomatome_net", "name": "カルチョまとめブログ", "url": "http://www.calciomatome.net/index.rdf"},
    {"id": "2ch_matomenews_com", "name": "まにゅそく 2chまとめニュース速報VIP", "url": "http://2ch-matomenews.com/feed"},
    {"id": "lions_matome_com_archives_category_e8_a5_bf_e6_ad_a6", "name": "やみ速@なんJ西武まとめ", "url": "https://lions-matome.com/archives/category/%E8%A5%BF%E6%AD%A6/feed"},
    {"id": "blog_livedoor_jp_coleblog", "name": "2ch東方スレ観測所", "url": "http://blog.livedoor.jp/coleblog/index.rdf"},
    {"id": "nofootynolife_net", "name": "NO FOOTY NO LIFE", "url": "http://nofootynolife.net/?xml"},
    {"id": "1000mg_jp", "name": "1000mg", "url": "http://1000mg.jp/feed"},
    {"id": "blog_livedoor_jp_kidandan", "name": "気団談", "url": "http://blog.livedoor.jp/kidandan/index.rdf"},
    {"id": "kaigainohannoublog_blog55_fc2_com", "name": "【海外の反応】　パンドラの憂鬱", "url": "http://kaigainohannoublog.blog55.fc2.com/?xml"},
    {"id": "www_otonarisoku_com", "name": "海外の反応　お隣速報", "url": "https://www.otonarisoku.com/feed"},
    {"id": "football_2ch_com", "name": "フットボール速報", "url": "http://football-2ch.com/index.rdf"},
    {"id": "www_negisoku_com", "name": "ネギ速", "url": "http://www.negisoku.com/index.rdf"},
    {"id": "blog_livedoor_jp_corez18c24_mili777", "name": "軍事・ミリタリー速報☆彡", "url": "http://blog.livedoor.jp/corez18c24-mili777/index.rdf"},
    {"id": "blog_livedoor_jp_hawksmatome", "name": "鷹速@ホークスまとめブログ", "url": "http://blog.livedoor.jp/hawksmatome/index.rdf"},
    {"id": "mona_news_com", "name": "モナニュース", "url": "http://mona-news.com/index.rdf"},
    {"id": "dng65_com", "name": "どんぐりこ - 海外の反応", "url": "http://dng65.com/?xml"},
    {"id": "www_netamesi_com", "name": "ネタめし.com", "url": "http://www.netamesi.com/index.rdf"},
    {"id": "blog_livedoor_jp_bmaysu", "name": "ってなんじぇですかー", "url": "http://blog.livedoor.jp/bmaysu/index.rdf"},
    {"id": "i2chmeijin_blog_fc2_com", "name": "2ch名人", "url": "http://i2chmeijin.blog.fc2.com/?xml"},
    {"id": "kandatasokuho_blog_fc2_com", "name": "カンダタ速報", "url": "http://kandatasokuho.blog.fc2.com/?xml"},
    {"id": "switchsoku_com", "name": "SWITCH速報", "url": "http://switchsoku.com/feed"},
    {"id": "anihatsu_com", "name": "アニはつ -アニメ発信場-", "url": "http://anihatsu.com/index.rdf"},
    {"id": "kemochan_com", "name": "けもちゃん", "url": "http://kemochan.com/feed"},
    {"id": "blog_livedoor_jp_drazuli", "name": "暇は無味無臭の劇薬", "url": "http://blog.livedoor.jp/drazuli/index.rdf"},
    {"id": "sow_blog_jp", "name": "すらるど - 海外の反応", "url": "http://sow.blog.jp/index.rdf"},
    {"id": "lovelivematocha_com", "name": "ラブライブ！まとめちゃんねる！！", "url": "http://lovelivematocha.com/?xml"},
    {"id": "visual_matome_com", "name": "V系まとめ速報", "url": "http://visual-matome.com/index.rdf"},
    {"id": "www_watch2chan_com", "name": "watch＠２ちゃんねる", "url": "http://www.watch2chan.com/index.rdf"},
    {"id": "ff14hikasensokuhou_com", "name": "FF14ひかせん速報", "url": "https://ff14hikasensokuhou.com/?xml"},
    {"id": "www_all_nationz_com", "name": "海外の万国反応記＠海外の反応", "url": "http://www.all-nationz.com/index.rdf"},
    {"id": "galapagosjapan_blog_fc2_com", "name": "ガラパゴスジャパン - 海外の反応", "url": "http://galapagosjapan.blog.fc2.com/?xml"},
    {"id": "ge_soku_com", "name": "げぇ速", "url": "http://ge-soku.com/index.rdf"},
    {"id": "nmb48_mtm_com", "name": "NMB48まとめスピリッツ", "url": "http://nmb48-mtm.com/index.rdf"},
    {"id": "www_japohan_net", "name": "じゃぽにか反応帳", "url": "http://www.japohan.net/feed"},
    {"id": "shingekikyojin_net", "name": "進撃の巨人ちゃんねる", "url": "http://shingekikyojin.net/index.rdf"},
    {"id": "foreignnews_biz_archives_cat_382414_xml", "name": "海外の反応 | 海外報道翻訳所", "url": "http://foreignnews.biz/archives/cat_382414.xml"},
    {"id": "blog_livedoor_jp_soccerrevolution", "name": "サッカーレボリューション", "url": "http://blog.livedoor.jp/soccerrevolution/index.rdf"},
    {"id": "pokemon_goh_doorblog_jp", "name": "NEWSぽけまとめーる", "url": "http://pokemon-goh.doorblog.jp/index.rdf"},
    {"id": "squallchannel_doorblog_jp", "name": "スコールちゃんねる｜２ちゃんまとめブログ", "url": "http://squallchannel.doorblog.jp/index.rdf"},
    {"id": "inutomo11_com", "name": "なんJクエスト", "url": "http://inutomo11.com/index.rdf"},
    {"id": "majimanjisokuhou_com", "name": "マジ卍速報", "url": "http://majimanjisokuhou.com/index.rdf"},
    {"id": "girlsreport_net", "name": "がーるずレポート - ガールズちゃんねるまとめブログ", "url": "http://girlsreport.net/index.rdf"},
    {"id": "www_mudainodocument_com", "name": "無題のドキュメント", "url": "http://www.mudainodocument.com/index.rdf"},
    {"id": "fesoku_net", "name": "ふぇー速", "url": "http://fesoku.net/index.rdf"},
    {"id": "www_okutta_net", "name": "億ったー", "url": "http://www.okutta.net/index.rdf"},
    {"id": "chomangasokuho_blog_jp", "name": "超・マンガ速報", "url": "http://chomangasokuho.blog.jp/index.rdf"},
    {"id": "shitsumon_aru_net", "name": "質問ある？まとめ速報", "url": "http://shitsumon-aru.net/index.rdf"},
    {"id": "blog_livedoor_jp_sky_wing2010_geinou", "name": "芸能人ニュース速報", "url": "http://blog.livedoor.jp/sky_wing2010-geinou/index.rdf"},
    {"id": "kidanlog_com", "name": "気団ログ", "url": "http://kidanlog.com/feed"},
    {"id": "kininaru_geinou_m_blog_jp", "name": "気になる芸能まとめ", "url": "http://kininaru-geinou-m.blog.jp/index.rdf"},
    {"id": "hiraganakeyaki_blog_jp", "name": "日向坂46まとめ速報", "url": "http://hiraganakeyaki.blog.jp/index.rdf"},
    {"id": "seikeidouga_blog_jp", "name": "政経ワロスまとめニュース♪", "url": "http://seikeidouga.blog.jp/index.rdf"},
    {"id": "kyousoku_net", "name": "今日速2ch", "url": "http://kyousoku.net/index.rdf"},
    {"id": "masked_blog_jp", "name": "ヒーローNEWS", "url": "http://masked.blog.jp/index.rdf"},
    {"id": "haronbouchannel_com", "name": "ハロン棒ch　-競馬まとめ-", "url": "http://haronbouchannel.com/index.rdf"},
    {"id": "pachislotzone_com", "name": "スロパチゾーン　パチンコパチスロまとめ", "url": "http://pachislotzone.com/feed"},
    {"id": "sonicch_com", "name": "ソニック速報", "url": "http://sonicch.com/index.rdf"},
    {"id": "girlsvip_matome_com", "name": "ガールズVIPまとめ", "url": "http://girlsvip-matome.com/index.rdf"},
    {"id": "www_anige_sokuhouvip_com", "name": "アニゲー速報", "url": "http://www.anige-sokuhouvip.com/?xml"},
    {"id": "www_moeruasia_net", "name": "もえるあじあ(･∀･)", "url": "https://www.moeruasia.net/index.rdf"},
    {"id": "gabiyori_com", "name": "げーあにびより｜ゲームやアニメの評価・感想まとめ", "url": "http://gabiyori.com/feed"},
    {"id": "crx7601_com", "name": "おーるじゃんる", "url": "http://crx7601.com/index.rdf"},
    {"id": "www_oumaga_times_com", "name": "おうまがタイムズ", "url": "http://www.oumaga-times.com/index.rdf"},
    {"id": "mashlife_doorblog_jp", "name": "mashlife通信", "url": "http://mashlife.doorblog.jp/index.rdf"},
    {"id": "eegg_fun", "name": "easterEgg", "url": "http://eegg.fun/index.rdf"},
    {"id": "you1news_com", "name": "U-1 NEWS", "url": "https://you1news.com/feed"},
    {"id": "blog_livedoor_jp_g_ogasawara", "name": "NaNじぇい", "url": "http://blog.livedoor.jp/g_ogasawara/index.rdf"},
    {"id": "www_fx2ch_net", "name": "FX2ちゃんねる|投資系2chまとめ", "url": "http://www.fx2ch.net/feed"},
    {"id": "mudasure_com", "name": "ムダスレ無き改革", "url": "http://mudasure.com/?xml"},
    {"id": "no_one_no_net", "name": "QQQ(海外の反応)", "url": "http://no-one-no.net/index.rdf"},
    {"id": "newsoku_blog", "name": "NEWSOKU BLOG", "url": "https://newsoku.blog/feed"},
    {"id": "konoyubitomare_jp", "name": "コノユビ", "url": "http://konoyubitomare.jp/index.rdf"},
    {"id": "ramen2ch_com", "name": "ラーメン速報｜2chまとめブログ", "url": "http://ramen2ch.com/?xml"},
    {"id": "totalwar_doorblog_jp", "name": "/)；｀ω´)＜国家総動員報", "url": "http://totalwar.doorblog.jp/index.rdf"},
    {"id": "www_kokunanmonomousu_com", "name": "国難にあってもの申す！！", "url": "http://www.kokunanmonomousu.com/index.rdf"},
    {"id": "rakukan_net", "name": "楽韓Web", "url": "http://rakukan.net/index.rdf"},
    {"id": "jishin_yogen_com", "name": "大地震・前兆・予言.com", "url": "https://jishin-yogen.com/?xml"},
    {"id": "kaigainoomaera_com", "name": "海外のお前ら　海外の反応", "url": "https://kaigainoomaera.com/?xml"},
    {"id": "kasegeru_blog_jp", "name": "稼げるまとめ速報", "url": "http://kasegeru.blog.jp/index.rdf"},
    {"id": "thainokoe_com", "name": "タイの反応 タイコエ", "url": "https://thainokoe.com/feed/"},
    {"id": "2chnewsblog_blog_jp", "name": "２ちゃんねるニュース超速まとめ＋", "url": "http://2chnewsblog.blog.jp/index.rdf"},
    {"id": "sumaburayasan_com", "name": "スマブラ屋さん | スマブラSPまとめ攻略", "url": "http://sumaburayasan.com/index.rdf"},
    {"id": "ginnga_blog_jp", "name": "銀河系まとめブログ", "url": "http://ginnga.blog.jp/index.rdf"},
    {"id": "www_jisaka_com", "name": "汎用型自作PCまとめ", "url": "http://www.jisaka.com/index.rdf"},
    {"id": "toushichannel_net", "name": "投資ちゃんねる", "url": "http://toushichannel.net/index.rdf"},
    {"id": "jumpmatome2ch_biz", "name": "ジャンプまとめ速報", "url": "http://jumpmatome2ch.biz/feed"},
    {"id": "kaikore_blogspot_com_feeds_posts_default_alt", "name": "かいこれ！ 海外の反応 コレクション", "url": "https://kaikore.blogspot.com/feeds/posts/default?alt=rss"},
    {"id": "xxhuyuzero_jp", "name": "フィギュアスケートまとめ零", "url": "http://xxhuyuzero.jp/feed"},
    {"id": "bluebluesunset_blog_fc2_com", "name": "ねこのあまやどり", "url": "http://bluebluesunset.blog.fc2.com/?xml"},
    {"id": "kokopyon_net", "name": "あぁ^～こころがぴょんぴょんするんじゃぁ^～", "url": "http://kokopyon.net/?xml"},
    {"id": "na2ka4_blog_fc2_com", "name": "あのころの", "url": "http://na2ka4.blog.fc2.com/?xml"},
    {"id": "airlinehonpo_blog_fc2_com", "name": "エアライン本舗", "url": "http://airlinehonpo.blog.fc2.com/?xml"},
    {"id": "money_life_doorblog_jp", "name": "マネーライフ2ch|クレジット関連・お金関係", "url": "http://money-life.doorblog.jp/index.rdf"},
    {"id": "ideal2ch_livedoor_biz", "name": "理想ちゃんねる", "url": "http://ideal2ch.livedoor.biz/index.rdf"},
    {"id": "www_movient_net", "name": "映画.net", "url": "http://www.movient.net/index.rdf"},
    {"id": "www_gadget2ch_com", "name": "ガジェット2ch", "url": "http://www.gadget2ch.com/index.rdf"},
    {"id": "blog_livedoor_jp_qmanews", "name": "くまニュース", "url": "http://blog.livedoor.jp/qmanews/index.rdf"},
    {"id": "suresuta_jp", "name": "すれすた", "url": "http://suresuta.jp/feed"},
    {"id": "nijimen_net", "name": "にじめん", "url": "http://nijimen.net/index.rdf"},
    {"id": "pachinkopachisro_com", "name": "パチンコ・パチスロ.com", "url": "http://pachinkopachisro.com/index.rdf"},
    {"id": "de_baystars_doorblog_jp", "name": "De速", "url": "http://de-baystars.doorblog.jp/index.rdf"},
    {"id": "blog_livedoor_jp_bluejay01_review", "name": "PCパーツまとめ", "url": "http://blog.livedoor.jp/bluejay01-review/index.rdf"},
    {"id": "ebitsu_net", "name": "えび通", "url": "http://ebitsu.net/index.rdf"},
    {"id": "blog_livedoor_jp_otomatome", "name": "音まとめ", "url": "http://blog.livedoor.jp/otomatome/index.rdf"},
    {"id": "polandball_blog_fc2_com", "name": "ポーランドボール 翻訳", "url": "http://polandball.blog.fc2.com/?xml"},
    {"id": "overseasresponse_com", "name": "海外の反応ジャーナル", "url": "https://overseasresponse.com/feed"},
    {"id": "blog_livedoor_jp_zzcj", "name": "海外反応！　I LOVE JAPAN", "url": "http://blog.livedoor.jp/zzcj/index.rdf"},
    {"id": "yaraon_blog_com", "name": "やらおん！", "url": "http://yaraon-blog.com/feed"},
    {"id": "blog_livedoor_jp_itsoku", "name": "IT速報", "url": "http://blog.livedoor.jp/itsoku/index.rdf"},
    {"id": "pawawa_sokuho_org_index20", "name": "ぱわわ速報", "url": "http://pawawa.sokuho.org/index20.rdf"},
    {"id": "beasoku_com_index20", "name": "ベア速", "url": "http://beasoku.com/index20.rdf"},
    {"id": "matmebae_net_index20", "name": "まとめ映ぇぇ", "url": "http://matmebae.net/index20.rdf"},
    {"id": "mildch_com", "name": "マイルドちゃんねる", "url": "http://mildch.com/index.rdf"},
    {"id": "blog_livedoor_jp_sasuga801_koukokugyoukai", "name": "アドちゃんねる", "url": "http://blog.livedoor.jp/sasuga801-koukokugyoukai/index.rdf"},
    {"id": "labaq_com_archives_cat_50037985_xml", "name": "らばQ - 海外の反応", "url": "http://labaq.com/archives/cat_50037985.xml"},
    {"id": "stumbleon_blog_fc2_com", "name": "こんなニュースにでくわした", "url": "http://stumbleon.blog.fc2.com/?xml"},
    {"id": "babymetalize_com", "name": "BABYMETALIZE", "url": "http://babymetalize.com/feed"},
    {"id": "eigotoka_com", "name": "eigotoka 　〜海外スレ翻訳所〜", "url": "https://eigotoka.com/feed"},
    {"id": "blog_livedoor_jp_kashikou", "name": "「日中文化交流」と書いてオタ活動と読む", "url": "http://blog.livedoor.jp/kashikou/index.rdf"},
    {"id": "mykeibamemory_blog_fc2_com", "name": "海外の小反応", "url": "http://mykeibamemory.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_sekaiminzoku", "name": "世界の憂鬱 海外・韓国の反応", "url": "http://blog.livedoor.jp/sekaiminzoku/index.rdf"},
    {"id": "coffeehonyaku_blogspot_com_feeds_posts_default_alt_rss_orderby_published", "name": "コーヒーと翻訳", "url": "https://coffeehonyaku.blogspot.com/feeds/posts/default?alt=rss&orderby=published"},
    {"id": "kaigaiwelcome_com", "name": "海外さんいらっしゃい　海外の反応", "url": "https://kaigaiwelcome.com/?xml"},
    {"id": "www_kaisupo_com_rss_xml_alt", "name": "海外の反応スポーツ", "url": "https://www.kaisupo.com/rss.xml?alt=rss"},
    {"id": "grandfleet_info", "name": "航空万能論GF", "url": "https://grandfleet.info/feed/"},
    {"id": "incident_wo_com", "name": "日本第一！ニュース録", "url": "https://incident-wo.com/feed/"},
    {"id": "himayomi_com", "name": "暇読み", "url": "https://himayomi.com/feed"},
    {"id": "tiktok_p_blog_jp", "name": "まとめＴｏｋ", "url": "http://tiktok-p.blog.jp/index.rdf"},
    {"id": "beikokukabu_etf_matome_com", "name": "米国株ETFまとめ速報", "url": "http://beikokukabu-etf-matome.com/index.rdf"},
    {"id": "keyakizaka46ch_jp", "name": "櫻坂46まとめちゃんねる", "url": "https://keyakizaka46ch.jp/feed"},
    {"id": "j_seiji_blog_jp", "name": "なんJ政治ネタまとめ", "url": "http://j-seiji.blog.jp/index.rdf"},
    {"id": "smasoku_blog_jp", "name": "スマッシュ速報", "url": "http://smasoku.blog.jp/index.rdf"},
    {"id": "blog_livedoor_jp_tohopoke", "name": "徒歩のポケモンまとめブログ", "url": "http://blog.livedoor.jp/tohopoke/index.rdf"},
    {"id": "srwmatome_com", "name": "スパロボまとめ速報", "url": "https://srwmatome.com/feed"},
    {"id": "highfashionmens_com", "name": "ハイファッションちゃんねる", "url": "https://highfashionmens.com/feed"},
    {"id": "gfoodd_com", "name": "明日は何を食べようか", "url": "http://gfoodd.com/feed"},
    {"id": "www_mutyun_com", "name": "mutyunのゲーム+αブログ", "url": "https://www.mutyun.com/feed"},
    {"id": "financial_c_net", "name": "守銭奴日報", "url": "https://financial-c.net/feed"},
    {"id": "www_mgif_jp", "name": "エムジフ～音ゲー情報局(MGIF)～", "url": "http://www.mgif.jp/index.rdf"},
    {"id": "zatuzatu_com", "name": "雑なまとめ", "url": "https://zatuzatu.com/feed"},
    {"id": "lucky318b_m50_coreserver_jp", "name": "Glauber通信", "url": "http://lucky318b.m50.coreserver.jp/feed"},
    {"id": "katasumisokuhou_blog_jp", "name": "かたすみ速報", "url": "http://katasumisokuhou.blog.jp/index.rdf"},
    {"id": "umaumanews_com", "name": "競馬まとめのまとめ", "url": "http://umaumanews.com/feed"},
    {"id": "www_fatego_matome_com", "name": "FGOまとめ速報", "url": "https://www.fatego-matome.com/feed/"},
    {"id": "datsuaron_blog_jp", "name": "脱亜論", "url": "http://datsuaron.blog.jp/index.rdf"},
    {"id": "xn_mckr6j9b9367e_com", "name": "ロマサガRS攻略まとめ隊", "url": "https://xn--mckr6j9b9367e.com/feed"},
    {"id": "xn_gdkl0dubtwb7e_net", "name": "モンハンワールド攻略まとめ隊", "url": "https://xn--gdkl0dubtwb7e.net/feed"},
    {"id": "xn_o9j0bk5t7exbwe_com", "name": "スマブラ攻略まとめ隊", "url": "https://xn--o9j0bk5t7exbwe.com/feed"},
    {"id": "xn_fgo_gh8fn72e_com", "name": "FGO攻略まとめ隊", "url": "https://xn--fgo-gh8fn72e.com/feed"},
    {"id": "netizen_voice_blog_jp", "name": "ネラーボイス", "url": "http://netizen-voice.blog.jp/index.rdf"},
    {"id": "keyakizaka46matomemory_net", "name": "欅坂46まとめもり～", "url": "http://keyakizaka46matomemory.net/index.rdf"},
    {"id": "46matome_net", "name": "日向坂46まとめもり～", "url": "http://46matome.net/index.rdf"},
    {"id": "moerunihon_blog_jp", "name": "もえるにほん彡(^)(^)", "url": "http://moerunihon.blog.jp/index.rdf"},
    {"id": "jumpmatome2ch_net", "name": "超・ジャンプまとめ速報", "url": "https://jumpmatome2ch.net/feed"},
    {"id": "pokemongo_kouryakumatome_net", "name": "ポケモンGO攻略まとめ速報！！", "url": "http://pokemongo-kouryakumatome.net/index.rdf"},
    {"id": "shikaku105_blog_jp", "name": "2chNEWSまとめ", "url": "http://shikaku105.blog.jp/index.rdf"},
    {"id": "basketballbbs_com", "name": "バスケまとめ・COM", "url": "http://basketballbbs.com/feed/"},
    {"id": "butumori_com", "name": "どうぶつの森まとめ速報", "url": "http://butumori.com/index.rdf"},
    {"id": "holosoku_com", "name": "ホロ速", "url": "https://holosoku.com/feed/"},
    {"id": "brow2ing_com", "name": "ブラブラブラウジング", "url": "http://brow2ing.com/index.rdf"},
    {"id": "betweenjpandkr_blog", "name": "ニチカン!", "url": "https://betweenjpandkr.blog/feed"},
    {"id": "www_2monkeys_jp", "name": "2chまとめ・読み物・長編・名作/2MONKEYS.JP", "url": "http://www.2monkeys.jp/index.rdf"},
    {"id": "precurematome_com", "name": "プリキュアのまとめ", "url": "http://precurematome.com/feed/"},
    {"id": "blog_livedoor_jp_kumokumowatawata", "name": "コイン速報 | 仮想通貨ニュース・暗号資産相場情報・5chまとめ", "url": "http://blog.livedoor.jp/kumokumowatawata/index.rdf"},
    {"id": "blog_livedoor_jp_waruneko00326_002", "name": "歴史的速報", "url": "http://blog.livedoor.jp/waruneko00326-002/index.rdf"},
    {"id": "jiwachan_net", "name": "じわるチャンネル-雑談まとめブログ-", "url": "http://jiwachan.net/index.rdf"},
    {"id": "fgochaldeas_com", "name": "FGOまとめ　カルデア速報", "url": "http://fgochaldeas.com/index.rdf"},
    {"id": "dsara_blog_fc2_com", "name": "ネット民の反応：国内・海外のゲーム・アニメの反応まとめ！", "url": "https://dsara.blog.fc2.com/?xml"},
    {"id": "vtubernews_jp", "name": "VTuberNews", "url": "http://vtubernews.jp/index.rdf"},
    {"id": "blog_livedoor_jp_madoyuka", "name": "ゲーハーの窓", "url": "http://blog.livedoor.jp/madoyuka//index.rdf"},
    {"id": "geolog_book_com", "name": "ジオろぐ", "url": "http://geolog-book.com/index.rdf"},
    {"id": "nida_aru_com", "name": "ニダアル速報＋", "url": "http://nida-aru.com/index.rdf"},
    {"id": "blog_livedoor_jp_nanjmagnus", "name": "なんＪは加速している", "url": "http://blog.livedoor.jp/nanjmagnus/index.rdf"},
    {"id": "pachinkolist_com", "name": "ぱちんこドキュメント!!", "url": "http://pachinkolist.com/index.rdf"},
    {"id": "shitsumonaru_com", "name": "為になる？質問ある？まとめ", "url": "http://shitsumonaru.com/feed"},
    {"id": "vtuber_matomeruyon_blog_jp", "name": "Vtuberまとめるよ～ん", "url": "http://vtuber-matomeruyon.blog.jp/index.rdf"},
    {"id": "o2military_blog_jp", "name": "軍事・ミリタリーログ", "url": "http://o2military.blog.jp/index.rdf"},
    {"id": "uma_log_net", "name": "うまろぐ", "url": "https://uma-log.net/feed/"},
    {"id": "geinou_7days_net", "name": "芸能7days", "url": "http://geinou-7days.net/feed"},
    {"id": "www_ballparksokuhou_com", "name": "ボールパーク速報 海外の反応", "url": "https://www.ballparksokuhou.com/?xml"},
    {"id": "marutoo_com", "name": "まるっと翻訳", "url": "https://marutoo.com/feed"},
    {"id": "azurlane_sokuhou_com_feed", "name": "アズレン速報", "url": "https://azurlane-sokuhou.com/?feed=rss2"},
    {"id": "jijinews_online", "name": "時事ネタニュース速報", "url": "http://jijinews.online/index.rdf"},
    {"id": "oishiimatome_com", "name": "おいしいまとめ", "url": "https://oishiimatome.com/?xml"},
    {"id": "hpupdate_info_feed", "name": "ハロアップデート", "url": "https://hpupdate.info/?feed=rss2"},
    {"id": "df_browser_games_com", "name": "ブラウザゲーム速報", "url": "https://df-browser-games.com/?xml"},
    {"id": "nogizakajyoho46_com", "name": "ネタンゴ！", "url": "https://nogizakajyoho46.com/index.rdf"},
    {"id": "ad_ars_line_blog_feed", "name": "Collect animations", "url": "https://ad-ars-line.blog/?feed=rss2"},
    {"id": "reddit_matome_com", "name": "Ask Reddit まとめ", "url": "https://reddit-matome.com/feed"},
    {"id": "sekai_zukan_blog", "name": "世界反応図鑑", "url": "https://sekai-zukan.blog/feed/"},
    {"id": "nogizakalife_tokyo_feed", "name": "乃木坂LIFE -坂道・48高速まとめ-", "url": "https://nogizakalife.tokyo/?feed=rss2"},
    {"id": "red4_kaigaimatome_com", "name": "Red4 海外の反応まとめ", "url": "https://red4-kaigaimatome.com/feed/"},
    {"id": "keizai4567_blog_jp", "name": "投資.com", "url": "https://keizai4567.blog.jp/index.rdf"},
    {"id": "halospo_com", "name": "ハロスポ＠ハロプロまとめ", "url": "https://halospo.com/feed/"},
    {"id": "sekahan0623_com", "name": "せかはん（世界の反応）", "url": "https://sekahan0623.com/feed"},
]
